### ISSUE TITLE
Good name for the colloquium series

### ISSUE THREAD

**Issue by ofchurches** [ofchurches/HARC_Development#3]
I remember you having a good name for the colloquium series @Lukah0173. But I don't remember what it was. Do you remember?
I've detailed our conversations so far [here](https://github.com/ofchurches/HARC_Development/blob/main/brief_2/CoP_for_data_in_SA_MD.md#colloquia). Feel free to make changes or let me know.

**Comment by Lukah0173** [comment]
Thank you for organising this Owen.

I've been thinking over names for this, my initial thoughts were something like:

**South Australian Digital Health Innovation Interest Group**

But it's still thoughts in progress. Would be great to think over and iterate with you :star2:

**Comment by ofchurches** [comment]
Thanks Lukah. I like it!
